### PR TITLE
UI of hero page improved

### LINKED ISSUE #5: Improve the UI of the Hero section
Screenshot from 2022-10-03 11-40-41
UI of this section is to be improved.
Note: The color scheme and font style needs to be same as in all pages.

### PR DESCRIPTION
**Pull request by amitmishra11**
@mishrashree18 Have a look!
I added the Hover effects wherever needed, and changed the font size in the nav as it seemed too small for the nav bar.
Also, I changed the layout in the Hero section.
As it looked pretty good before also just some things were missing but now I think by making these changes it would look better.
Do suggest changes.

Resolves #5

### CODE REVIEW

**Comment by amitmishra11** [comment]
image

Screenshot (311)

Screenshot (312)

**Comment by amitmishra11** [comment]
@mishrashree18  any suggestions?

**Comment by mishrashree18** [comment]
> @mishrashree18 any suggestions?

merged 👍🏼

**Comment by amitmishra11** [comment]
@mishrashree18 please give hacktoberfest accepted tag to the merged PR

**Comment by mishrashree18** [comment]
> @mishrashree18 please give hacktoberfest accepted tag to the merged PR

done

**Pull request merged**
